const ACCESS_TOKEN_LIFE_TIME = "15m";
const REFRESH_TOKEN_LIFE_TIME = "1d";
const DEVELOPMENT_TOKEN_LIFE_TIME = "30d";
const JWT_SECRET = "microservice";

const USERS_SERVICE_ADDRESS = "http://127.0.0.1:7000";
const PRESCRIPTIONS_SERVICE_ADDRESS = "http://127.0.0.1:8000";
const PRESCRIPTIONS_VIEW_SERVICE_ADDRESS = "http://127.0.0.1:9000";
const STATISTICS_SERVICE_ADDRESS = "http://127.0.0.1:10000";

const SALT_HASH_LENGTH = 16;

module.exports = {
    ACCESS_TOKEN_LIFE_TIME,
    REFRESH_TOKEN_LIFE_TIME,
    DEVELOPMENT_TOKEN_LIFE_TIME,
    JWT_SECRET,
    SALT_HASH_LENGTH,
    USERS_SERVICE_ADDRESS,
    PRESCRIPTIONS_SERVICE_ADDRESS,
    PRESCRIPTIONS_VIEW_SERVICE_ADDRESS,
    STATISTICS_SERVICE_ADDRESS
}