# Generated by Django 4.0 on 2022-01-01 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptionapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('national_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
    ]
