# Generated by Django 4.0 on 2021-12-29 22:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0003_alter_patient_national_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='national_code',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^[0-9]*$', message='incorrect national code'), django.core.validators.MinLengthValidator(10, message='incorrect national code')]),
        ),
    ]
