# Generated by Django 4.0 on 2021-12-29 23:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0004_alter_patient_national_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('national_code', models.CharField(max_length=10, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^[0-9]*$', message='national code must be only digits'), django.core.validators.MinLengthValidator(10, message='length of national code must be exactly 10')])),
                ('name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='NewDoctorEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('national_code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='patient',
            name='national_code',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^[0-9]*$', message='national code must be only digits'), django.core.validators.MinLengthValidator(10, message='length of national code must be exactly 10')]),
        ),
    ]
