# Generated by Django 4.0 on 2022-01-01 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0006_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='id',
        ),
        migrations.AlterField(
            model_name='admin',
            name='user_name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
