# Generated by Django 4.0 on 2022-01-07 18:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0008_remove_admin_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='name',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(1, message='name must not be empty')]),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='password',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(1, message='password must not be empty')]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='name',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(1, message='name must not be empty')]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='password',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(1, message='password must not be empty')]),
        ),
    ]
