# Generated by Django 4.0 on 2022-01-08 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('new_prescriptions_count', models.IntegerField(default=0)),
                ('new_patients_count', models.IntegerField(default=0)),
                ('new_doctors_count', models.IntegerField(default=0)),
            ],
        ),
    ]
