# Generated by Django 4.0 on 2022-01-08 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statisticsapp', '0002_doctor_patient_prescription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailystatistic',
            name='id',
        ),
        migrations.AlterField(
            model_name='dailystatistic',
            name='date',
            field=models.DateField(primary_key=True, serialize=False),
        ),
    ]
